# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eadf22dc9b3f38af7e1035bff536e47d89031dc8397eb654ff1bb851737fc15cfedfcdfd5844abee4fcd0d2e818a0f7a783f639a86bf8b9eb7e1720008a8733d

test:
  secret_key_base: e845cbe942784c8a84afd20d6c4c5c9806601a97b9da565e5f48a02cd56cf59b9ac3eb5e8e17dad271fd46e7c31f6ade76c6ab8c2aef953fc3d6142865356e9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
